services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.1.4
    ports:
      - "8282:8080"
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    command: [ "start-dev" ]