services:
  keycloak:
    image: quay.io/keycloak/keycloak:20.0.3
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      DB_VENDOR: h2
    ports:
      - "8282:8080"
    command:
      - start-dev